### ISSUE TITLE
bug: extra trailing slash added during update

### ISSUE THREAD

**Issue by king8fisher** [LeoDog896/deno-outdated#18]
```
"imports": {
  "preact/": "https://esm.sh/preact@10.19.2/",
}
```
after the run turns into 
```
"imports": {
  "preact/": "https://esm.sh/preact@10.19.2//",
}
```
with the extra trailing `/`

**Comment by tristan-f-r** [comment]
Fixed by https://github.com/LeoDog896/deno-outdated/commit/9d02d50ae655b37c5009109f85f00e15caa7b731 and published in [0.2.5](https://deno.land/x/deno_outdated@0.2.5).
